id: I6489ECE9
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:13:02.067748'
last_modified: '2022-05-31T05:13:02.067753'
parser: null
source_metadata:
  title: Menlungpa Mikyö Dorje
  language: bo
  description: 'Texts by and about Menlungpa Mikyö Dorje (sman lung pa mi bskyod rdo
    rje, b. 12th C.):'
  volume:
    f638B:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      base_file: f638B.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
